name: Flutter macOS Build

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers only on version tags like v1.0.0

jobs:
  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Enable macOS build
        run: flutter config --enable-macos-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build macOS app
        run: flutter build macos

      - name: List Release Folder
        run: ls -la build/macos/Build/Products/Release

      - name: Check if build output exists
        run: |
          if [ ! -d "build/macos/Build/Products/Release/Runner.app" ]; then
            echo "Runner.app not found. Build may have failed."
            exit 1
          fi

      - name: Create DMG
        run: |
          cd build/macos/Build/Products/Release
          hdiutil create -volname StickNoteWidget \
                         -srcfolder "Runner.app" \
                         -ov -format UDZO StickNoteWidget.dmg
          mv StickNoteWidget.dmg ../../../../StickNoteWidget-macOS.dmg

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: StickNoteWidget-macOS
          path: build/StickNoteWidget-macOS.dmg

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/StickNoteWidget-macOS.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
