name: Flutter Desktop Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  APP_NAME: StickNoteWidget
  FLUTTER_VERSION: '3.29.3'

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Enable Windows build
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Clean old builds
        run: flutter clean

      - name: Remove CMake cache (Windows)
        run: Remove-Item -Recurse -Force build\windows
        shell: powershell

      - name: Run tests (non-blocking)
        run: flutter test || true

      - name: Build Windows
        run: flutter build windows

      - name: Verify build output
        run: |
          if (!(Test-Path "build/windows/x64/runner/Release/${{ env.APP_NAME }}.exe")) {
            Write-Error "${{ env.APP_NAME }}.exe not found. Build may have failed."
            exit 1
          }
        shell: powershell

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Zip Windows build
        run: |
          Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath artifacts/${{ env.APP_NAME }}-Windows.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-Windows
          path: artifacts/${{ env.APP_NAME }}-Windows.zip

      - name: Release Windows build
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/${{ env.APP_NAME }}-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Enable macOS build
        run: flutter config --enable-macos-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Clean old builds
        run: flutter clean

      - name: Run tests (non-blocking)
        run: flutter test || true

      - name: Build macOS
        run: flutter build macos

      - name: List release folder
        run: ls -l build/macos/Build/Products/Release

      - name: Check macOS build output
        run: |
          echo "Checking for ${{ env.APP_NAME }}.app..."
          if [ ! -d "build/macos/Build/Products/Release/${{ env.APP_NAME }}.app" ]; then
            echo "${{ env.APP_NAME }}.app not found. Build may have failed."
            exit 1
          fi

      - name: Code sign macOS app
        if: env.MACOS_SIGNING_CERT != ''
        run: |
          codesign --force --deep --sign "${MACOS_SIGNING_CERT}" build/macos/Build/Products/Release/${{ env.APP_NAME }}.app
        env:
          MACOS_SIGNING_CERT: ${{ secrets.MACOS_SIGNING_CERT }}

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Create macOS DMG
        run: |
          cd build/macos/Build/Products/Release
          hdiutil create -volname ${{ env.APP_NAME }} \
                         -srcfolder "${{ env.APP_NAME }}.app" \
                         -ov -format UDZO ${{ env.APP_NAME }}.dmg
          mv ${{ env.APP_NAME }}.dmg ../../../../artifacts/${{ env.APP_NAME }}-macOS.dmg

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-macOS
          path: artifacts/${{ env.APP_NAME }}-macOS.dmg

      - name: Release macOS build
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/${{ env.APP_NAME }}-macOS.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
