name: Flutter Desktop Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Enable Windows build
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows

      - name: Zip .exe for release
        run: |
          Compress-Archive -Path build\windows\runner\Release\* -DestinationPath StickNoteWidget-Windows.zip

      - name: Upload .exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: StickNoteWidget-Windows
          path: StickNoteWidget-Windows.zip

      - name: Upload to GitHub Release (Windows)
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: StickNoteWidget-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Enable macOS build
        run: flutter config --enable-macos-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build macOS
        run: flutter build macos

      - name: Check if build output exists
        run: |
          if [ ! -d "build/macos/Build/Products/Release/Runner.app" ]; then
            echo "Runner.app not found. Build may have failed."
            exit 1
          fi

      - name: Create DMG
        run: |
          cd build/macos/Build/Products/Release
          hdiutil create -volname StickNoteWidget \
                         -srcfolder "Runner.app" \
                         -ov -format UDZO StickNoteWidget.dmg
          mv StickNoteWidget.dmg ../../../../StickNoteWidget-macOS.dmg

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: StickNoteWidget-macOS
          path: build/StickNoteWidget-macOS.dmg

      - name: Upload to GitHub Release (macOS)
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/StickNoteWidget-macOS.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
