name: Build Linux

on:
  push:
    branches: [main]
    tags:
      - 'v*' # e.g. v1.0.0

permissions:
  contents: write      

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: stable

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgtk-3-dev squashfs-tools desktop-file-utils libfuse2

      - name: Build Linux app
        run: flutter build linux

      - name: Prepare AppDir structure
        run: |
          mkdir -p AppDir/usr/bin
          cp -r build/linux/x64/release/bundle/* AppDir/usr/bin/
          mkdir -p AppDir/usr/share/applications
          cat > AppDir/usr/share/applications/stickynote.desktop <<EOF
          [Desktop Entry]
          Type=Application
          Name=StickyNoteWidget
          Exec=StickyNoteWidget
          Icon=stickynote
          Categories=Utility;
          EOF

      - name: Download AppImageTool
        run: |
          wget -q https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Create AppImage
        run: |
          ./appimagetool-x86_64.AppImage AppDir StickyNoteWidget-${{ github.ref_name }}.AppImage

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: StickyNoteWidget-${{ github.ref_name }}.AppImage

  release:
    needs: [build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: release-assets/linux

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: release-assets/linux/StickyNoteWidget-${{ github.ref_name }}.AppImage
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: false
          makeLatest: legacy
          replacesArtifacts: true
