name: "Build"

on:
  push:
    branches: [main]

jobs:
  build-macos:
    name: Build Android, iOS, macOS
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'


      - name: Install Dependencies
        run: flutter pub get

      - name: Build macOS App
        run: flutter build macos

      - name: Compress iOS and macOS Builds
        run: |
          cd build
          tar -czf macos_build.tar.gz macos

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases-macos
          path: |
            build/macos_build.tar.gz


      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/macos_build.tar.gz
          tag: v${{ env.VERSION }}
          token: ${{ secrets.TOKEN }}

  build-windows:
    name: Build Windows App
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows App
        run: flutter build windows

      - name: Compress Windows Build
        run: Compress-Archive -Path build\windows -DestinationPath build\windows_build.zip

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Releases-windows
          path: build/windows_build.zip
